version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}applicationregistry-api:${APPLICATIONREGISTRY_VERSION:-latest}
    networks:
      - application-registry
    environment:
      ASPNETCORE_URLS: "https://+:443;http://+:80"
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost/swagger/v1/swagger.json"]
  ui:
    image: ${DOCKER_REGISTRY-}applicationregistry-ui:${APPLICATIONREGISTRY_VERSION:-latest}

    networks:
      - application-registry
  gateway:
    image: ${DOCKER_REGISTRY-}applicationregistry-gateway:${APPLICATIONREGISTRY_VERSION:-latest}
    ports:
      - 10000:10000    
      - 9903:9903    
    networks:
      - application-registry

networks:
  application-registry: