//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApplicationRegistry.Infrastructure.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ApplicationRegistry.Infrastructure.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ;
        ///with T as (
        ///	select 
        ///	*,
        ///	ROW_NUMBER() OVER(PARTITION BY a.IdApplication, a.IdEnvironment
        ///                                 ORDER BY a.createDate DESC) AS rk
        ///	from ApplicationVersion a
        ///	where a.IsArchived = 0 /*and a.IdApplication = @IdApplication*/
        ///)
        ///update T
        ///set IsArchived = 1
        ///where rk &gt; 1.
        /// </summary>
        internal static string MarkPreviousVersionsAsArchived {
            get {
                return ResourceManager.GetString("MarkPreviousVersionsAsArchived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to swagger: &quot;2.0&quot;
        ///info:
        ///  description: &quot;This is a sample server Petstore server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters.&quot;
        ///  version: &quot;1.0.0&quot;
        ///  title: &quot;Swagger Petstore&quot;
        ///  termsOfService: &quot;http://swagger.io/terms/&quot;
        ///  contact:
        ///    email: &quot;apiteam@swagger.io&quot;
        ///  license:
        ///    name: &quot;Apache 2.0&quot;
        ///    url: &quot;ht [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SwaggerDemo {
            get {
                return ResourceManager.GetString("SwaggerDemo", resourceCulture);
            }
        }
    }
}
