using ApplicationRegistry.Database.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace ApplicationRegistry.Database.EntityConfigurators
{
    class ProjectEntityConfiguration : EntityTypeConfigurationBase<SystemEntity>
    {
        public override void ConfigureEntity(EntityTypeBuilder<SystemEntity> builder)
        {
            builder.ToTable("Systems");

            builder.HasData(
                new SystemEntity(SystemEntity.UnasignedApplications, "Unasigned applications", Consts.CreateDate) { Description = "Project for applications generated by CLI" }
            );
        }
    }
}
