using ApplicationRegistry.Database.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace ApplicationRegistry.Database.EntityConfigurators
{
    class ProjectEntityConfiguration : EntityTypeConfigurationBase<ProjectEntity>
    {
        public override void ConfigureEntity(EntityTypeBuilder<ProjectEntity> builder)
        {
            builder.ToTable("Projects");

            builder.HasData(
                new ProjectEntity(ProjectEntity.UnasignedApplications, "Unasigned applications", Consts.CreateDate) { Description = "Project for applications generated by CLI" }
            );
        }
    }
}
