using ApplicationRegistry.Database.Entities;
using ApplicationRegistry.Infrastructure.EntityConfigurators;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace ApplicationRegistry.Database.EntityConfigurators
{
    class SystemEntityConfiguration : EntityTypeConfigurationBase<SystemEntity>
    {
        public override void ConfigureEntity(EntityTypeBuilder<SystemEntity> builder)
        {
            builder.ToTable("Systems");

            builder.Property(e => e.Name)
                .IsName();

            builder.Property(e => e.Description)
                .IsDescription();

            builder.HasData(
                new SystemEntity(SystemEntity.UnasignedApplications, "Unasigned applications", Consts.CreateDate) { Description = "Project for applications generated by CLI" }
            );
        }
    }
}
